FROM php:7-fpm

# 替换为国内阿里镜像
COPY ./sources/debain-bullseye-source.list /etc/apt/sources.list

# 安装系统包和PHP扩展(此处以Yii 2.0 Framework所需为例)
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions \
    soap \
    zip \
    curl \
    bcmath \
    exif \
    gd \
    iconv \
    intl \
    mbstring \
    opcache \
    pcntl \
    posix \
    pdo_mysql \
    pdo_pgsql

# 安装PHP Imagick扩展
RUN apt-get update && \
    apt-get install -y libmagickwand-dev && \
    pecl install http://pecl.php.net/get/imagick-3.7.0.tgz && \
    docker-php-ext-enable imagick

# 安装PHP Memcached扩展
RUN apt-get update && \
    apt-get install -y libz-dev libmemcached-dev && \
    pecl install http://pecl.php.net/get/memcached-3.2.0.tgz && \
    docker-php-ext-enable memcached

# 安装PHP Redis扩展
RUN pecl install http://pecl.php.net/get/redis-5.3.7.tgz && \
    docker-php-ext-enable redis

# 安装PHP Mongodb扩展
RUN pecl install http://pecl.php.net/get/mongodb-1.14.2.tgz && \
    docker-php-ext-enable mongodb

# 安装PHP Swoole扩展
RUN pecl install http://pecl.php.net/get/swoole-4.8.12.tgz && \
    docker-php-ext-enable swoole

# 安装PHP Decimal扩展
RUN apt-get update && \
    apt-get install -y libmpdec-dev && \
    pecl install http://pecl.php.net/get/decimal-2.0.0.tgz && \
    docker-php-ext-enable decimal


# 安装相关系统软件服务
RUN apt-get update \
    && apt-get install -y --force-yes \
        cron \
        supervisor \
        procps \
        dos2unix \
    --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# 设置时区
ENV TIME_ZONE Asia/Shanghai
# ENV TIME_ZONE UTC
RUN echo "${TIME_ZONE}" > /etc/timezone \
    && ln -sf /usr/share/zoneinfo/${TIME_ZONE} /etc/localtime

# 设置系统编码
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# 允许Composer作为root运行
ENV COMPOSER_ALLOW_SUPERUSER 1

# 安装Composer
COPY ./config/usr.local.bin/composer /usr/local/bin/composer
RUN chmod 755 /usr/local/bin/composer
RUN curl -sS https://install.phpcomposer.com/installer | php -- \
        --version=2.4.4 \
        --filename=composer.phar \
        --install-dir=/usr/local/bin && \
    composer clear-cache
# 更换为阿里云镜像
RUN composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/

COPY ./config/php-fpm.conf /usr/local/etc/php-fpm.conf
COPY ./config/conf.d/ /usr/local/etc/php/conf.d/

# (Debian only) Change www-data user ID
# ENV PHP_USER_ID 1000
# RUN set -x \
#     && userdel www-data \
#     && groupadd -g ${PHP_USER_ID} -r www-data \
#     && useradd -u ${PHP_USER_ID} -r -g www-data www-data

WORKDIR /opt/htdocs

EXPOSE 9000
